services:
  webportsystem.api:
    image: ${DOCKER_REGISTRY-}webportsystemapi
    build:
      context: .
      dockerfile: src/api/WebportSystem.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_URLS=http://+:8080  

  webportsystem.dashboard:
    image: ${DOCKER_REGISTRY-}webportsystemdashboard
    build:
      context: .
      dockerfile: src/apps/blazor-server/WebportSystem.Dashboard/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
