services:
  webportsystem.api:
    image: ghcr.io/saifdevopz/webportsystem-api:latest
    build:
      context: .
      dockerfile: src/api/WebportSystem.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_URLS=http://+:8080

  webportsystem.dashboard:
    image: ghcr.io/saifdevopz/webportsystem-dashboard:latest
    build:
      context: .
      dockerfile: src/apps/blazor-server/WebportSystem.Dashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
 
  webportsystem.pos:
    image: ghcr.io/saifdevopz/webportsystem-pos:latest
    build:
      context: .
      dockerfile: src/apps/WebportSystem.POS/Dockerfile
    container_name: webportsystem-pos
    ports:
      - "4200:4200"
    volumes:
      - ./src/apps/WebportSystem.POS:/app
      - /app/node_modules  
    environment:
      - STYLE=css

