# Ignore S125 (commented-out code) in Razor files
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S125
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.razor