name: WebportSystem.API CI/CD

on:
  workflow_dispatch:

jobs:
  build_image:
    name: Package Software
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/webportsystem-api
          TAG=$(echo $GITHUB_SHA | cut -c1-7)

          # Build the API image using docker-compose build
          docker compose -f docker-compose.yml build webportsystem.api

          # Tag the image with commit SHA
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG

          # Push both tags
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG
    
      - name: Trigger Portainer Webhook
        run: |
          curl -X POST "https://portainer.webport.co.za/api/webhooks/f36f5ff7-a894-4979-b0b5-48777e479dd1"          





