name: WebportSystem.POS CI/CD

on:
  workflow_dispatch:

jobs:
  build_image:
    name: Package Software
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/webportsystem-pos
          TAG=${GITHUB_SHA::7}

          echo "Building image with tag: $TAG"

          # Build image
          docker compose -f docker-compose.yml build webportsystem.pos

          # Tag image
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG

          # Push both tags
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG

          echo "✅ Image pushed: $IMAGE_NAME:$TAG"

  update_server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build_image

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        env:
          IMAGE_TAG: ${{ github.sha }}
          GHCR_PAT: ${{ secrets.GH_PAT }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: IMAGE_TAG,GHCR_PAT
          script: |
            set -e

            # Generate short SHA tag
            echo "Full IMAGE_TAG from GitHub: $IMAGE_TAG"
            SHORT_TAG=${IMAGE_TAG::7}
            echo "🚀 Deploying image tag: $SHORT_TAG"

            if [ -z "$SHORT_TAG" ]; then
              echo "❌ ERROR: SHORT_TAG is empty"
              exit 1
            fi

            echo "🚀 Deploying image tag: $SHORT_TAG"

            cd /home/webportsystem-pos

            # Login to GHCR on manager node (credentials sent to workers)
            #echo "$GHCR_PAT" | docker login ghcr.io -u saifdevopz --password-stdin

            # Optional: pull the image first to ensure all nodes have it
            #docker pull ghcr.io/saifdevopz/webportsystem-pos:$SHORT_TAG

            IMAGE_TAG=$SHORT_TAG docker stack deploy \
              --with-registry-auth \
              -c docker-stack.yaml \
              webportsystem-pos

            echo "✅ Deployment complete"
